version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  app-node:
    build:
      context: ./backend
      dockerfile: go.dockerfile
    container_name: app-node
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
      REGION: us-east-1
      DYNAMO_ENDPOINT: http://dynamodb-local:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: node.dockerfile
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - app-node
    environment:
      NEXT_PUBLIC_API_URL: http://app-node:8080
    command: ["npm", "run", "dev"]
